# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Domain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain

  target 'DomainTests' do
    # Pods for testing
  end

end

target 'NetworkPlatform' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkPlatform

  target 'NetworkPlatformTests' do
    # Pods for testing
  end

end

target '{{cookiecutter.app_name}}' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for {{cookiecutter.app_name}}

  target '{{cookiecutter.app_name}}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '{{cookiecutter.app_name}}UITests' do
    # Pods for testing
  end

end
